server:
  port: 8080
  mode: debug

database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: yourpassword
  dbname: go_mall
  charset: utf8mb4
  parse_time: true
  loc: Local

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0

jwt:
  secret: your_jwt_secret_key_here
  expire_hours: 24

wechat:
  appid: your_wechat_appid
  secret: your_wechat_secret 